apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml --namespace=hoeeeeeh --controller statefulset convert
    kompose.version: 1.31.0 (a04ecdb9e)
  creationTimestamp: null
  labels:
    io.kompose.service: outstagram
  name: outstagram
  namespace: hoeeeeeh
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: outstagram
  serviceName: outstagram
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/outstargram-default: "true"
        io.kompose.service: outstagram
    spec:
      containers:
        - image: jakeheon/outstagram
          name: outstagram-app
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
  updateStrategy: {}
status:
  availableReplicas: 0
  replicas: 0
